language: c
compiler:
  - gcc

sudo: true
dist: trusty

addons:
  apt:
    packages:
    - u-boot-tools
#    - coccinelle

before_install:
  #- sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ raring main universe"
  - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ xenial main universe"
  - sudo apt-get -qq update
  - sudo apt-get install -qq gcc-mips-linux-gnu coccinelle sparse

git:
  depth: 1

before_script:
    # https://lists.ozlabs.org/pipermail/linuxppc-dev/2017-December/166830.html
    - rm -f .cache.mk

script:
    - make ARCH=mips ci20_defconfig
    - make -j2 ARCH=mips CROSS_COMPILE=mips-linux-gnu- uImage W=1 C=1
    #- make ARCH=mips CROSS_COMPILE=mips-linux-gnu- uImage C=1
    - make coccicheck MODE=report ARCH=mips M=arch/mips/kernel J=1

notifications:
    email:
      recipients:
            - malat@debian.org
      on_success: always
      on_failure: always
