language: c
compiler:
  - gcc

dist: trusty

addons:
  apt:
    packages:
      - gcc-powerpc-linux-gnu

git:
  depth: 1

before_script:
    # https://lists.ozlabs.org/pipermail/linuxppc-dev/2017-December/166830.html
    - rm -f .cache.mk

env:
  matrix:
    - ARCH=powerpc
      DEF=g4
    - ARCH=powerpc
      DEF=pmac32

script:
    #- make -j2 ARCH=powerpc CROSS_COMPILE=powerpc-linux-gnu- #V=1
    - make ARCH=$ARCH ${DEF}_defconfig V=1
    - make -j2 ARCH=$ARCH CROSS_COMPILE=powerpc-linux-gnu- W=1

notifications:
    email:
      recipients:
            - malat@debian.org
      on_success: always
      on_failure: always
